// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2V2rQv3R-SeG07gH0WaASFzEkiXVfM58',
    appId: '1:103965560010:web:2c385eaa1706fba1fdf833',
    messagingSenderId: '103965560010',
    projectId: 'flutter-app-c3c49',
    authDomain: 'flutter-app-c3c49.firebaseapp.com',
    databaseURL: 'https://flutter-app-c3c49-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-c3c49.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPGx4LHW4J1ILye52zeriJIwiXQaYdtOo',
    appId: '1:103965560010:android:4c0b6a8fce01d6d8fdf833',
    messagingSenderId: '103965560010',
    projectId: 'flutter-app-c3c49',
    databaseURL: 'https://flutter-app-c3c49-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-c3c49.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2V2rQv3R-SeG07gH0WaASFzEkiXVfM58',
    appId: '1:103965560010:web:dd8d7127f9f3a74afdf833',
    messagingSenderId: '103965560010',
    projectId: 'flutter-app-c3c49',
    authDomain: 'flutter-app-c3c49.firebaseapp.com',
    databaseURL: 'https://flutter-app-c3c49-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-app-c3c49.appspot.com',
  );
}
